[tool.poetry]
name = "agency"
version = "1.0.2"
description = "A fast and minimal actor model framework for integrating AI, human, and other computing systems"
authors = ["Daniel Rodriguez"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
asyncio = "^3.4"
colorama = "^0.4"
pydantic = "^1.8"
transformers = "^4.29"
torch = "^2.0"
Flask-SocketIO = "^5.3"
eventlet = "^0.33"
openai = "^0.27.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
